name: ci

on: pull_request
jobs: 
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        python-version: ['3.10', '3.11']
      
    steps:

      - name: Baixa o repositório
        uses: actions/checkout@v4

      - name: Baixa as diferentes versões do Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - name: Instala as dependências
        run: pip install -r requirements.txt 
      
      - name: Testa o contrato de entrada
        run: pytest tests/test_contrato_in.py -v 
              
      - name: Testa o contrato de saída
        run: pytest tests/test_contrato_out.py -v